services:

  cf-py-env:
    image: pypy:3.10
    container_name: cf-py-env
    volumes:
      - ./py/src:/usr/src
    tty: true

  cf-go-env:
    image: golang:1.22.2
    container_name: cf-go-env
    volumes:
      - ./go/src:/usr/src
    tty: true
