version: "3"

tasks:
  # python
  py:start:
    cmds:
      - task py:up && task py:exec
  py:up:
    cmds:
      - docker compose up -d cf-py-env
  py:down:
    cmds:
      - docker compose down cf-py-env
  py:exec:
    cmds:
      - docker exec -it cf-py-env bash -c "cd /usr/src && exec bash"

  # go
  go:start:
    cmds:
      - task go:up && task go:exec
  go:up:
    cmds:
      - docker compose up -d cf-go-env
  go:down:
    cmds:
      - docker compose down cf-go-env
  go:exec:
    cmds:
      - docker exec -it cf-go-env bash -c "cd /usr/src && exec bash"
